# src: ./.github/workflows/ci-scan-secrets.yml
# @(#) : Caller workflow for secret scanning in .github repository
#
# Copyright (c) 2025- atsushifx <https://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

name: "CI Scan Secrets"

# Minimal permissions following security best practices
permissions:
  contents: read

on:
  push:

  pull_request:
    branches:
      - main
      - master
      - releases

  workflow_dispatch:

jobs:
  scan-gitleaks:
    name: Gitleaks Secret Scan
    permissions:
      contents: read
    uses: aglabo/.github/.github/workflows/ci-common-scan-gitleaks.yml@r1.1.2
